// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Base/Footer.vue')['default']
    HaveATry: typeof import('./src/components/Home/HaveATry.vue')['default']
    IntroAutumn: typeof import('./src/components/Introduction/IntroAutumn.vue')['default']
    IntroCard: typeof import('./src/components/Home/IntroCard.vue')['default']
    IntroEbits: typeof import('./src/components/Introduction/IntroEbits.vue')['default']
    IntroPlanets: typeof import('./src/components/Introduction/IntroPlanets.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MineCard: typeof import('./src/components/Mine/MineCard.vue')['default']
    MineInfo: typeof import('./src/components/Mine/MineInfo.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/ProductCard.vue')['default']
    ProductCardCol: typeof import('./src/components/ProductCard/ProductCardCol.vue')['default']
    ProductGridView: typeof import('./src/components/ProductsLists/ProductGridView.vue')['default']
    ProductListView: typeof import('./src/components/ProductsLists/ProductListView.vue')['default']
    ProductRowView: typeof import('./src/components/ProductsLists/ProductRowView.vue')['default']
    RadioChoice: typeof import('./src/components/Questionare/RadioChoice.vue')['default']
    RecommendProducts: typeof import('./src/components/Home/RecommendProducts.vue')['default']
    Sample: typeof import('./src/components/sample.vue')['default']
    TitleSort: typeof import('./src/components/Sundry/TitleSort.vue')['default']
    TopCar: typeof import('./src/components/Home/TopCar.vue')['default']
  }
}

export { }
